{% set name = "bw2data" %}
{% set version = "4.0.dev22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 210cd87819a9d469b3d842b9c8ca72db196ace049693901af6ef77c5b7d5528f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - bw2-uptodate = bw2data.bin.bw2_uptodate:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - bw2parameters
    - bw2calc >=2.0.dev13
    - bw_processing
    - bw-projects
    - lxml
    - numpy
    - peewee >=3.9.4
    - platformdirs
    - python >=3.9
    - requests >=1.1.0
    - scipy
    - stats_arrays
    - tqdm
    - voluptuous
    - whoosh
    - wrapt

test:
  imports:
    - bw2data
  requires:
    - pip
  commands:
    - pip check
    # No test of bw2-uptodate as no --help or --version available

about:
  home: https://github.com/brightway-lca/brightway2-data
  summary: Tools for the management of inventory databases and impact assessment methods. Part of the Brightway2 LCA Framework.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/brightway2-data

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
